### PR TITLE
Fix 50glob.t when run as root.

### PR DESCRIPTION
**Pull request by FGasper**
Fixes issue #3.

### CODE REVIEW

**Comment by markov2** [comment]
Ah, well found.  You're right.

I think this patch is not sufficient: when people do login as root, then their real-uid is also root.

**Comment by FGasper** [comment]
The patch fixes the test for me when I log in as root, I think because the EUID is what determines access to a directory, not the RUID?

**Comment by markov2** [comment]
Yes, the Effected-UID is the one which determines access, and be be changed via set(r|re|res|)uid.  Your login uid is the Real-UID.  But if that is 'root' as well, then you patch does not work.  I'll make a work-around for that case.  Thank you for your contribution!

**Comment by FGasper** [comment]
> Yes, the Effected-UID is the one which determines access, and be be changed via set(r|re|res|)uid. Your login uid is the Real-UID. But if that is 'root' as well, then you patch does not work. I'll make a work-around for that case. Thank you for your contribution!

Do you mind giving an example? I’m logging in as root—all IDs in sight are 0—and the patch as I submitted it works:
```
root@felipe 09:37:57 50glob_root_fix ~/fg_code/perl5-POSIX-1003
> prove -wlvmb t/50glob.t
t/50glob.t ..
ok 1 - ran glob
ok 2 - found filenames
ok 3 - match /etc
ok 4
ok 5
ok 6 - error fn
ok 7 - error rc
ok 8
1..8
ok
All tests successful.
Files=1, Tests=8,  0 wallclock secs ( 0.03 usr  0.01 sys +  0.09 cusr  0.01 csys =  0.14 CPU)
Result: PASS

OK
root@felipe 09:38:11 50glob_root_fix ~/fg_code/perl5-POSIX-1003
> perl -E'say for $>, $<, $), $('
0
0
0 0
0 0
```

**Comment by markov2** [comment]
O wait, I am hurrying myself, and should study your suggestion better.  My mind is distracted.  The normal way to drop  permissions, is to say "$> = $<".
I have no idea whether there are security mechanisms around which do block your trick... let's see.  Patch will be applied (and attributed to you ;-)

**Comment by markov2** [comment]
Released as 1.02

**Pull request merged**
